#!/bin/bash
set -ex
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
export MANPATH=/tmp/
export NVM_DIR="/home/vagrant/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
source ~/.nvm/nvm.sh 
nvm install stable
nvm use stable
cd /build
git clone https://github.com/posix4e/browser-laptop-bootstrap
cd browser-laptop-bootstrap
npm run init
npm run build

